# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hnsw_l2_nns <- function(index_name, mat, ef, search_k, grain_size = 1L, include_distances = TRUE, verbose = FALSE) {
    .Call(`_RcppHNSW_hnsw_l2_nns`, index_name, mat, ef, search_k, grain_size, include_distances, verbose)
}

hnsw_cosine_nns <- function(index_name, mat, ef, search_k, grain_size = 1L, include_distances = TRUE, verbose = FALSE) {
    .Call(`_RcppHNSW_hnsw_cosine_nns`, index_name, mat, ef, search_k, grain_size, include_distances, verbose)
}

hnsw_ip_nns <- function(index_name, mat, ef, search_k, grain_size = 1L, include_distances = TRUE, verbose = FALSE) {
    .Call(`_RcppHNSW_hnsw_ip_nns`, index_name, mat, ef, search_k, grain_size, include_distances, verbose)
}

